### ISSUE TITLE
Install pygimli

### ISSUE THREAD

**Issue by asaintenoy** [Chouzekriterres/Kriterres#2]
Nous avons regardé ensemble hier. Sur l'ordi de nicolas, l'erreur venait qu'il faut réinstaller un miniconda tout neuf tout propre pour pouvoir ensuite avoir pygimli qui marche.
Sinon il va chercher des vieux trucs qui sont plus à jour...

**Comment by ELEGER** [comment]
Super!

**Comment by asaintenoy** [comment]
Evidemment après il faut réinstaller toutes les dépendances, du genre numpy,...

**Comment by ELEGER** [comment]
Oui, c'est la ou je voulais en venir, c'est un peu chiant de repartir d'une install toute propre... on en revient a mon idee de tout reformatter hein :)

**Comment by asaintenoy** [comment]
Boaf... on n'a pas tant de trucs que ça non? Je suis en train de le faire sur mon ordi. 
Nico disait que c'est une bonne habitude... Et il ne devrait pas y avoir de problème de path car ca s'installe qu'en local sur le compte de chacun...

**Comment by ELEGER** [comment]
J'ai un peu peur de ficher le bordel moi. Je vais d'abord le faire sur mon ordi peros avant de le lancer sur celui du lab

**Comment by asaintenoy** [comment]
En tous les cas, sur mon ordi ça y est. Quand Clémence arrive je le tente sur son compte sur cafe.

**Comment by nthiery** [comment]
Ouaip, tant qu'on a de la place disque, un bon réseau et qu'il y a des
paquets conda pour les dépendances, il suffit de tout fourrer dans le
environments.yml; la réinstallation complète est entièrement
automatique et ne prend que quelques minutes.

C'est effectivement essentiellement l'idée de reformater :-) Mais
c'est juste la pile logicielle sans la configuration du matériel, des
comptes utilisateurs, ...
